---
# Checking first if environment is compatible with this role
- name: Ensure compatibility with this role
  include_tasks: asserts.yml

# Installing vault on servers
- name: Ensure vault is installed (Rocky)
  include_tasks: install-rocky.yml
  when: ansible_distribution == 'Rocky'

# Configuring vault 
- name: Ensure vault configuration has been done as expected 
  include_tasks: configure.yml