---
- name: Restart vault 
  become: true
  ansible.builtin.systemd_service:
    name: vault 
    daemon_reload: true
    state: restarted

- name: Restart rsyslogd
  become: true
  service: name=rsyslog state=restarted